# Generated by Django 4.2.6 on 2023-10-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='dateTime',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventId',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='ticketPrice',
            new_name='ticket_price',
        ),
        migrations.AddField(
            model_name='event',
            name='available_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='total_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
