# Generated by Django 4.2.6 on 2023-10-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='eventId',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='numberOfTickets',
            new_name='number_of_tickets',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderId',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='totalAmount',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='userId',
            new_name='user_id',
        ),
    ]
