# Generated by Django 4.2.6 on 2023-10-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='orderId',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paymentId',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paymentMethod',
            new_name='payment_method',
        ),
    ]
