# Generated by Django 4.2.6 on 2023-10-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='eventId',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketId',
            new_name='ticket_id',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='userId',
            new_name='user_id',
        ),
    ]
