# Generated by Django 4.2.6 on 2023-11-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(default='Not Provided', max_length=255)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
