# Generated by Django 4.2.6 on 2023-10-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='venueId',
            new_name='venue_id',
        ),
    ]
